// Generated by CodiumAI
const {getEquipo, agregarEquipo, actualizarEquipo, eliminarEquipo, obtenerEquipoPorId} = require('../controllers/EquiposControler');
const xd = require('../services/db');


describe('agregarEquipo', () => {
  // Tests that the function validates that all required fields are present before attempting to add a new team
  it('should validate that all required fields are present', async () => {
    const req = {
      body: {
        idequipo: '1',
        nombreequipo: 'Team A',
        ciudad: 'City A',
        liga: 'League A'
      }
    };
    const res = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn()
    };
    await agregarEquipo(req, res);
    expect(res.status).toHaveBeenCalledWith(500);
    expect(res.json).toHaveBeenCalledWith({ error: 'Internal server error' });
  });
  // Tests that the function handles invalid date formats
  it('should handle invalid date formats', async () => {
    const req = {
      body: {
        idequipo: '1',
        nombreequipo: 'Team A',
        ciudad: 'City A',
        liga: 'League A',
        fecha: '2022-01-32'
      }
    };
    const res = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn()
    };
    await agregarEquipo(req, res);
    expect(res.status).toHaveBeenCalledWith(500);
    expect(res.json).toHaveBeenCalledWith({ error: 'Internal server error' });
  });


});
// Generated by CodiumAI

describe('actualizarEquipo', () => {


  // Tests that a success message is returned after updating the team's information
  // Tests that a 500 status code and an error message are returned if the SQL query fails
  it('should return a 500 status code and an error message if the SQL query fails', async () => {
    // Arrange
    const req = {
      params: { id: '1' },
      body: {
        nombreequipo: 'New Team',
        ciudad: 'New City',
        liga: 'New League',
        fecha: '2022-01-01'
      }
    };
    const res = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn()
    };
    const xdMock = jest.fn().mockRejectedValue(new Error('SQL query failed'));

    // Act
    await actualizarEquipo(req, res);

    // Assert
    expect(res.status).toHaveBeenCalledWith(500);
    expect(res.json).toHaveBeenCalledWith({ error: 'Internal server error' });
  });

});
// Generated by CodiumAI

